// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relay/relay.proto

package pbRelay // import "Open_IM/pkg/proto/relay"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import sdk_ws "Open_IM/pkg/proto/sdk_ws"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OnlinePushMsgReq struct {
	OperationID          string          `protobuf:"bytes,1,opt,name=OperationID" json:"OperationID,omitempty"`
	MsgData              *sdk_ws.MsgData `protobuf:"bytes,2,opt,name=msgData" json:"msgData,omitempty"`
	PushToUserID         string          `protobuf:"bytes,3,opt,name=pushToUserID" json:"pushToUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OnlinePushMsgReq) Reset()         { *m = OnlinePushMsgReq{} }
func (m *OnlinePushMsgReq) String() string { return proto.CompactTextString(m) }
func (*OnlinePushMsgReq) ProtoMessage()    {}
func (*OnlinePushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{0}
}
func (m *OnlinePushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlinePushMsgReq.Unmarshal(m, b)
}
func (m *OnlinePushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlinePushMsgReq.Marshal(b, m, deterministic)
}
func (dst *OnlinePushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlinePushMsgReq.Merge(dst, src)
}
func (m *OnlinePushMsgReq) XXX_Size() int {
	return xxx_messageInfo_OnlinePushMsgReq.Size(m)
}
func (m *OnlinePushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlinePushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_OnlinePushMsgReq proto.InternalMessageInfo

func (m *OnlinePushMsgReq) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

func (m *OnlinePushMsgReq) GetMsgData() *sdk_ws.MsgData {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *OnlinePushMsgReq) GetPushToUserID() string {
	if m != nil {
		return m.PushToUserID
	}
	return ""
}

type OnlinePushMsgResp struct {
	Resp                 []*SingleMsgToUserPlatform `protobuf:"bytes,1,rep,name=resp" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *OnlinePushMsgResp) Reset()         { *m = OnlinePushMsgResp{} }
func (m *OnlinePushMsgResp) String() string { return proto.CompactTextString(m) }
func (*OnlinePushMsgResp) ProtoMessage()    {}
func (*OnlinePushMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{1}
}
func (m *OnlinePushMsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlinePushMsgResp.Unmarshal(m, b)
}
func (m *OnlinePushMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlinePushMsgResp.Marshal(b, m, deterministic)
}
func (dst *OnlinePushMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlinePushMsgResp.Merge(dst, src)
}
func (m *OnlinePushMsgResp) XXX_Size() int {
	return xxx_messageInfo_OnlinePushMsgResp.Size(m)
}
func (m *OnlinePushMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlinePushMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_OnlinePushMsgResp proto.InternalMessageInfo

func (m *OnlinePushMsgResp) GetResp() []*SingleMsgToUserPlatform {
	if m != nil {
		return m.Resp
	}
	return nil
}

type SingelMsgToUserResultList struct {
	UserID               string                     `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Resp                 []*SingleMsgToUserPlatform `protobuf:"bytes,2,rep,name=resp" json:"resp,omitempty"`
	OnlinePush           bool                       `protobuf:"varint,3,opt,name=onlinePush" json:"onlinePush,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SingelMsgToUserResultList) Reset()         { *m = SingelMsgToUserResultList{} }
func (m *SingelMsgToUserResultList) String() string { return proto.CompactTextString(m) }
func (*SingelMsgToUserResultList) ProtoMessage()    {}
func (*SingelMsgToUserResultList) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{2}
}
func (m *SingelMsgToUserResultList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingelMsgToUserResultList.Unmarshal(m, b)
}
func (m *SingelMsgToUserResultList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingelMsgToUserResultList.Marshal(b, m, deterministic)
}
func (dst *SingelMsgToUserResultList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingelMsgToUserResultList.Merge(dst, src)
}
func (m *SingelMsgToUserResultList) XXX_Size() int {
	return xxx_messageInfo_SingelMsgToUserResultList.Size(m)
}
func (m *SingelMsgToUserResultList) XXX_DiscardUnknown() {
	xxx_messageInfo_SingelMsgToUserResultList.DiscardUnknown(m)
}

var xxx_messageInfo_SingelMsgToUserResultList proto.InternalMessageInfo

func (m *SingelMsgToUserResultList) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SingelMsgToUserResultList) GetResp() []*SingleMsgToUserPlatform {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *SingelMsgToUserResultList) GetOnlinePush() bool {
	if m != nil {
		return m.OnlinePush
	}
	return false
}

type OnlineBatchPushOneMsgReq struct {
	OperationID          string          `protobuf:"bytes,1,opt,name=OperationID" json:"OperationID,omitempty"`
	MsgData              *sdk_ws.MsgData `protobuf:"bytes,2,opt,name=msgData" json:"msgData,omitempty"`
	PushToUserIDList     []string        `protobuf:"bytes,3,rep,name=pushToUserIDList" json:"pushToUserIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OnlineBatchPushOneMsgReq) Reset()         { *m = OnlineBatchPushOneMsgReq{} }
func (m *OnlineBatchPushOneMsgReq) String() string { return proto.CompactTextString(m) }
func (*OnlineBatchPushOneMsgReq) ProtoMessage()    {}
func (*OnlineBatchPushOneMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{3}
}
func (m *OnlineBatchPushOneMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineBatchPushOneMsgReq.Unmarshal(m, b)
}
func (m *OnlineBatchPushOneMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineBatchPushOneMsgReq.Marshal(b, m, deterministic)
}
func (dst *OnlineBatchPushOneMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineBatchPushOneMsgReq.Merge(dst, src)
}
func (m *OnlineBatchPushOneMsgReq) XXX_Size() int {
	return xxx_messageInfo_OnlineBatchPushOneMsgReq.Size(m)
}
func (m *OnlineBatchPushOneMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineBatchPushOneMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineBatchPushOneMsgReq proto.InternalMessageInfo

func (m *OnlineBatchPushOneMsgReq) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

func (m *OnlineBatchPushOneMsgReq) GetMsgData() *sdk_ws.MsgData {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *OnlineBatchPushOneMsgReq) GetPushToUserIDList() []string {
	if m != nil {
		return m.PushToUserIDList
	}
	return nil
}

type OnlineBatchPushOneMsgResp struct {
	SinglePushResult     []*SingelMsgToUserResultList `protobuf:"bytes,1,rep,name=singlePushResult" json:"singlePushResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *OnlineBatchPushOneMsgResp) Reset()         { *m = OnlineBatchPushOneMsgResp{} }
func (m *OnlineBatchPushOneMsgResp) String() string { return proto.CompactTextString(m) }
func (*OnlineBatchPushOneMsgResp) ProtoMessage()    {}
func (*OnlineBatchPushOneMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{4}
}
func (m *OnlineBatchPushOneMsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineBatchPushOneMsgResp.Unmarshal(m, b)
}
func (m *OnlineBatchPushOneMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineBatchPushOneMsgResp.Marshal(b, m, deterministic)
}
func (dst *OnlineBatchPushOneMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineBatchPushOneMsgResp.Merge(dst, src)
}
func (m *OnlineBatchPushOneMsgResp) XXX_Size() int {
	return xxx_messageInfo_OnlineBatchPushOneMsgResp.Size(m)
}
func (m *OnlineBatchPushOneMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineBatchPushOneMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineBatchPushOneMsgResp proto.InternalMessageInfo

func (m *OnlineBatchPushOneMsgResp) GetSinglePushResult() []*SingelMsgToUserResultList {
	if m != nil {
		return m.SinglePushResult
	}
	return nil
}

type SingleMsgToUserPlatform struct {
	ResultCode           int64    `protobuf:"varint,1,opt,name=ResultCode" json:"ResultCode,omitempty"`
	RecvID               string   `protobuf:"bytes,2,opt,name=RecvID" json:"RecvID,omitempty"`
	RecvPlatFormID       int32    `protobuf:"varint,3,opt,name=RecvPlatFormID" json:"RecvPlatFormID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleMsgToUserPlatform) Reset()         { *m = SingleMsgToUserPlatform{} }
func (m *SingleMsgToUserPlatform) String() string { return proto.CompactTextString(m) }
func (*SingleMsgToUserPlatform) ProtoMessage()    {}
func (*SingleMsgToUserPlatform) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{5}
}
func (m *SingleMsgToUserPlatform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleMsgToUserPlatform.Unmarshal(m, b)
}
func (m *SingleMsgToUserPlatform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleMsgToUserPlatform.Marshal(b, m, deterministic)
}
func (dst *SingleMsgToUserPlatform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleMsgToUserPlatform.Merge(dst, src)
}
func (m *SingleMsgToUserPlatform) XXX_Size() int {
	return xxx_messageInfo_SingleMsgToUserPlatform.Size(m)
}
func (m *SingleMsgToUserPlatform) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleMsgToUserPlatform.DiscardUnknown(m)
}

var xxx_messageInfo_SingleMsgToUserPlatform proto.InternalMessageInfo

func (m *SingleMsgToUserPlatform) GetResultCode() int64 {
	if m != nil {
		return m.ResultCode
	}
	return 0
}

func (m *SingleMsgToUserPlatform) GetRecvID() string {
	if m != nil {
		return m.RecvID
	}
	return ""
}

func (m *SingleMsgToUserPlatform) GetRecvPlatFormID() int32 {
	if m != nil {
		return m.RecvPlatFormID
	}
	return 0
}

type GetUsersOnlineStatusReq struct {
	UserIDList           []string `protobuf:"bytes,1,rep,name=userIDList" json:"userIDList,omitempty"`
	OperationID          string   `protobuf:"bytes,2,opt,name=operationID" json:"operationID,omitempty"`
	OpUserID             string   `protobuf:"bytes,3,opt,name=opUserID" json:"opUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersOnlineStatusReq) Reset()         { *m = GetUsersOnlineStatusReq{} }
func (m *GetUsersOnlineStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetUsersOnlineStatusReq) ProtoMessage()    {}
func (*GetUsersOnlineStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{6}
}
func (m *GetUsersOnlineStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersOnlineStatusReq.Unmarshal(m, b)
}
func (m *GetUsersOnlineStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersOnlineStatusReq.Marshal(b, m, deterministic)
}
func (dst *GetUsersOnlineStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersOnlineStatusReq.Merge(dst, src)
}
func (m *GetUsersOnlineStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetUsersOnlineStatusReq.Size(m)
}
func (m *GetUsersOnlineStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersOnlineStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersOnlineStatusReq proto.InternalMessageInfo

func (m *GetUsersOnlineStatusReq) GetUserIDList() []string {
	if m != nil {
		return m.UserIDList
	}
	return nil
}

func (m *GetUsersOnlineStatusReq) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

func (m *GetUsersOnlineStatusReq) GetOpUserID() string {
	if m != nil {
		return m.OpUserID
	}
	return ""
}

type GetUsersOnlineStatusResp struct {
	ErrCode              int32                                     `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg               string                                    `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	SuccessResult        []*GetUsersOnlineStatusResp_SuccessResult `protobuf:"bytes,3,rep,name=successResult" json:"successResult,omitempty"`
	FailedResult         []*GetUsersOnlineStatusResp_FailedDetail  `protobuf:"bytes,4,rep,name=failedResult" json:"failedResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *GetUsersOnlineStatusResp) Reset()         { *m = GetUsersOnlineStatusResp{} }
func (m *GetUsersOnlineStatusResp) String() string { return proto.CompactTextString(m) }
func (*GetUsersOnlineStatusResp) ProtoMessage()    {}
func (*GetUsersOnlineStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{7}
}
func (m *GetUsersOnlineStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersOnlineStatusResp.Unmarshal(m, b)
}
func (m *GetUsersOnlineStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersOnlineStatusResp.Marshal(b, m, deterministic)
}
func (dst *GetUsersOnlineStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersOnlineStatusResp.Merge(dst, src)
}
func (m *GetUsersOnlineStatusResp) XXX_Size() int {
	return xxx_messageInfo_GetUsersOnlineStatusResp.Size(m)
}
func (m *GetUsersOnlineStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersOnlineStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersOnlineStatusResp proto.InternalMessageInfo

func (m *GetUsersOnlineStatusResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GetUsersOnlineStatusResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetUsersOnlineStatusResp) GetSuccessResult() []*GetUsersOnlineStatusResp_SuccessResult {
	if m != nil {
		return m.SuccessResult
	}
	return nil
}

func (m *GetUsersOnlineStatusResp) GetFailedResult() []*GetUsersOnlineStatusResp_FailedDetail {
	if m != nil {
		return m.FailedResult
	}
	return nil
}

type GetUsersOnlineStatusResp_SuccessDetail struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform" json:"platform,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	ConnID               string   `protobuf:"bytes,3,opt,name=connID" json:"connID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersOnlineStatusResp_SuccessDetail) Reset() {
	*m = GetUsersOnlineStatusResp_SuccessDetail{}
}
func (m *GetUsersOnlineStatusResp_SuccessDetail) String() string { return proto.CompactTextString(m) }
func (*GetUsersOnlineStatusResp_SuccessDetail) ProtoMessage()    {}
func (*GetUsersOnlineStatusResp_SuccessDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{7, 0}
}
func (m *GetUsersOnlineStatusResp_SuccessDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersOnlineStatusResp_SuccessDetail.Unmarshal(m, b)
}
func (m *GetUsersOnlineStatusResp_SuccessDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersOnlineStatusResp_SuccessDetail.Marshal(b, m, deterministic)
}
func (dst *GetUsersOnlineStatusResp_SuccessDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersOnlineStatusResp_SuccessDetail.Merge(dst, src)
}
func (m *GetUsersOnlineStatusResp_SuccessDetail) XXX_Size() int {
	return xxx_messageInfo_GetUsersOnlineStatusResp_SuccessDetail.Size(m)
}
func (m *GetUsersOnlineStatusResp_SuccessDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersOnlineStatusResp_SuccessDetail.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersOnlineStatusResp_SuccessDetail proto.InternalMessageInfo

func (m *GetUsersOnlineStatusResp_SuccessDetail) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *GetUsersOnlineStatusResp_SuccessDetail) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetUsersOnlineStatusResp_SuccessDetail) GetConnID() string {
	if m != nil {
		return m.ConnID
	}
	return ""
}

type GetUsersOnlineStatusResp_FailedDetail struct {
	UserID               string   `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersOnlineStatusResp_FailedDetail) Reset()         { *m = GetUsersOnlineStatusResp_FailedDetail{} }
func (m *GetUsersOnlineStatusResp_FailedDetail) String() string { return proto.CompactTextString(m) }
func (*GetUsersOnlineStatusResp_FailedDetail) ProtoMessage()    {}
func (*GetUsersOnlineStatusResp_FailedDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{7, 1}
}
func (m *GetUsersOnlineStatusResp_FailedDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersOnlineStatusResp_FailedDetail.Unmarshal(m, b)
}
func (m *GetUsersOnlineStatusResp_FailedDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersOnlineStatusResp_FailedDetail.Marshal(b, m, deterministic)
}
func (dst *GetUsersOnlineStatusResp_FailedDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersOnlineStatusResp_FailedDetail.Merge(dst, src)
}
func (m *GetUsersOnlineStatusResp_FailedDetail) XXX_Size() int {
	return xxx_messageInfo_GetUsersOnlineStatusResp_FailedDetail.Size(m)
}
func (m *GetUsersOnlineStatusResp_FailedDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersOnlineStatusResp_FailedDetail.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersOnlineStatusResp_FailedDetail proto.InternalMessageInfo

func (m *GetUsersOnlineStatusResp_FailedDetail) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUsersOnlineStatusResp_FailedDetail) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GetUsersOnlineStatusResp_FailedDetail) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type GetUsersOnlineStatusResp_SuccessResult struct {
	UserID               string                                    `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Status               string                                    `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	DetailPlatformStatus []*GetUsersOnlineStatusResp_SuccessDetail `protobuf:"bytes,3,rep,name=detailPlatformStatus" json:"detailPlatformStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *GetUsersOnlineStatusResp_SuccessResult) Reset() {
	*m = GetUsersOnlineStatusResp_SuccessResult{}
}
func (m *GetUsersOnlineStatusResp_SuccessResult) String() string { return proto.CompactTextString(m) }
func (*GetUsersOnlineStatusResp_SuccessResult) ProtoMessage()    {}
func (*GetUsersOnlineStatusResp_SuccessResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{7, 2}
}
func (m *GetUsersOnlineStatusResp_SuccessResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersOnlineStatusResp_SuccessResult.Unmarshal(m, b)
}
func (m *GetUsersOnlineStatusResp_SuccessResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersOnlineStatusResp_SuccessResult.Marshal(b, m, deterministic)
}
func (dst *GetUsersOnlineStatusResp_SuccessResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersOnlineStatusResp_SuccessResult.Merge(dst, src)
}
func (m *GetUsersOnlineStatusResp_SuccessResult) XXX_Size() int {
	return xxx_messageInfo_GetUsersOnlineStatusResp_SuccessResult.Size(m)
}
func (m *GetUsersOnlineStatusResp_SuccessResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersOnlineStatusResp_SuccessResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersOnlineStatusResp_SuccessResult proto.InternalMessageInfo

func (m *GetUsersOnlineStatusResp_SuccessResult) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUsersOnlineStatusResp_SuccessResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetUsersOnlineStatusResp_SuccessResult) GetDetailPlatformStatus() []*GetUsersOnlineStatusResp_SuccessDetail {
	if m != nil {
		return m.DetailPlatformStatus
	}
	return nil
}

type KickUserOfflineReq struct {
	OperationID          string   `protobuf:"bytes,1,opt,name=operationID" json:"operationID,omitempty"`
	PlatformID           int32    `protobuf:"varint,2,opt,name=platformID" json:"platformID,omitempty"`
	KickUserIDList       []string `protobuf:"bytes,3,rep,name=kickUserIDList" json:"kickUserIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickUserOfflineReq) Reset()         { *m = KickUserOfflineReq{} }
func (m *KickUserOfflineReq) String() string { return proto.CompactTextString(m) }
func (*KickUserOfflineReq) ProtoMessage()    {}
func (*KickUserOfflineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{8}
}
func (m *KickUserOfflineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickUserOfflineReq.Unmarshal(m, b)
}
func (m *KickUserOfflineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickUserOfflineReq.Marshal(b, m, deterministic)
}
func (dst *KickUserOfflineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickUserOfflineReq.Merge(dst, src)
}
func (m *KickUserOfflineReq) XXX_Size() int {
	return xxx_messageInfo_KickUserOfflineReq.Size(m)
}
func (m *KickUserOfflineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KickUserOfflineReq.DiscardUnknown(m)
}

var xxx_messageInfo_KickUserOfflineReq proto.InternalMessageInfo

func (m *KickUserOfflineReq) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

func (m *KickUserOfflineReq) GetPlatformID() int32 {
	if m != nil {
		return m.PlatformID
	}
	return 0
}

func (m *KickUserOfflineReq) GetKickUserIDList() []string {
	if m != nil {
		return m.KickUserIDList
	}
	return nil
}

type KickUserOfflineResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickUserOfflineResp) Reset()         { *m = KickUserOfflineResp{} }
func (m *KickUserOfflineResp) String() string { return proto.CompactTextString(m) }
func (*KickUserOfflineResp) ProtoMessage()    {}
func (*KickUserOfflineResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{9}
}
func (m *KickUserOfflineResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickUserOfflineResp.Unmarshal(m, b)
}
func (m *KickUserOfflineResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickUserOfflineResp.Marshal(b, m, deterministic)
}
func (dst *KickUserOfflineResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickUserOfflineResp.Merge(dst, src)
}
func (m *KickUserOfflineResp) XXX_Size() int {
	return xxx_messageInfo_KickUserOfflineResp.Size(m)
}
func (m *KickUserOfflineResp) XXX_DiscardUnknown() {
	xxx_messageInfo_KickUserOfflineResp.DiscardUnknown(m)
}

var xxx_messageInfo_KickUserOfflineResp proto.InternalMessageInfo

type MultiTerminalLoginCheckReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	PlatformID           int32    `protobuf:"varint,2,opt,name=platformID" json:"platformID,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	OperationID          string   `protobuf:"bytes,4,opt,name=operationID" json:"operationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiTerminalLoginCheckReq) Reset()         { *m = MultiTerminalLoginCheckReq{} }
func (m *MultiTerminalLoginCheckReq) String() string { return proto.CompactTextString(m) }
func (*MultiTerminalLoginCheckReq) ProtoMessage()    {}
func (*MultiTerminalLoginCheckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{10}
}
func (m *MultiTerminalLoginCheckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiTerminalLoginCheckReq.Unmarshal(m, b)
}
func (m *MultiTerminalLoginCheckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiTerminalLoginCheckReq.Marshal(b, m, deterministic)
}
func (dst *MultiTerminalLoginCheckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiTerminalLoginCheckReq.Merge(dst, src)
}
func (m *MultiTerminalLoginCheckReq) XXX_Size() int {
	return xxx_messageInfo_MultiTerminalLoginCheckReq.Size(m)
}
func (m *MultiTerminalLoginCheckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiTerminalLoginCheckReq.DiscardUnknown(m)
}

var xxx_messageInfo_MultiTerminalLoginCheckReq proto.InternalMessageInfo

func (m *MultiTerminalLoginCheckReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MultiTerminalLoginCheckReq) GetPlatformID() int32 {
	if m != nil {
		return m.PlatformID
	}
	return 0
}

func (m *MultiTerminalLoginCheckReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MultiTerminalLoginCheckReq) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

type MultiTerminalLoginCheckResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiTerminalLoginCheckResp) Reset()         { *m = MultiTerminalLoginCheckResp{} }
func (m *MultiTerminalLoginCheckResp) String() string { return proto.CompactTextString(m) }
func (*MultiTerminalLoginCheckResp) ProtoMessage()    {}
func (*MultiTerminalLoginCheckResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_f693b13cb6a37b62, []int{11}
}
func (m *MultiTerminalLoginCheckResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiTerminalLoginCheckResp.Unmarshal(m, b)
}
func (m *MultiTerminalLoginCheckResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiTerminalLoginCheckResp.Marshal(b, m, deterministic)
}
func (dst *MultiTerminalLoginCheckResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiTerminalLoginCheckResp.Merge(dst, src)
}
func (m *MultiTerminalLoginCheckResp) XXX_Size() int {
	return xxx_messageInfo_MultiTerminalLoginCheckResp.Size(m)
}
func (m *MultiTerminalLoginCheckResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiTerminalLoginCheckResp.DiscardUnknown(m)
}

var xxx_messageInfo_MultiTerminalLoginCheckResp proto.InternalMessageInfo

func (m *MultiTerminalLoginCheckResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *MultiTerminalLoginCheckResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*OnlinePushMsgReq)(nil), "relay.OnlinePushMsgReq")
	proto.RegisterType((*OnlinePushMsgResp)(nil), "relay.OnlinePushMsgResp")
	proto.RegisterType((*SingelMsgToUserResultList)(nil), "relay.SingelMsgToUserResultList")
	proto.RegisterType((*OnlineBatchPushOneMsgReq)(nil), "relay.OnlineBatchPushOneMsgReq")
	proto.RegisterType((*OnlineBatchPushOneMsgResp)(nil), "relay.OnlineBatchPushOneMsgResp")
	proto.RegisterType((*SingleMsgToUserPlatform)(nil), "relay.SingleMsgToUserPlatform")
	proto.RegisterType((*GetUsersOnlineStatusReq)(nil), "relay.GetUsersOnlineStatusReq")
	proto.RegisterType((*GetUsersOnlineStatusResp)(nil), "relay.GetUsersOnlineStatusResp")
	proto.RegisterType((*GetUsersOnlineStatusResp_SuccessDetail)(nil), "relay.GetUsersOnlineStatusResp.SuccessDetail")
	proto.RegisterType((*GetUsersOnlineStatusResp_FailedDetail)(nil), "relay.GetUsersOnlineStatusResp.FailedDetail")
	proto.RegisterType((*GetUsersOnlineStatusResp_SuccessResult)(nil), "relay.GetUsersOnlineStatusResp.SuccessResult")
	proto.RegisterType((*KickUserOfflineReq)(nil), "relay.KickUserOfflineReq")
	proto.RegisterType((*KickUserOfflineResp)(nil), "relay.KickUserOfflineResp")
	proto.RegisterType((*MultiTerminalLoginCheckReq)(nil), "relay.MultiTerminalLoginCheckReq")
	proto.RegisterType((*MultiTerminalLoginCheckResp)(nil), "relay.MultiTerminalLoginCheckResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Relay service

type RelayClient interface {
	OnlinePushMsg(ctx context.Context, in *OnlinePushMsgReq, opts ...grpc.CallOption) (*OnlinePushMsgResp, error)
	GetUsersOnlineStatus(ctx context.Context, in *GetUsersOnlineStatusReq, opts ...grpc.CallOption) (*GetUsersOnlineStatusResp, error)
	OnlineBatchPushOneMsg(ctx context.Context, in *OnlineBatchPushOneMsgReq, opts ...grpc.CallOption) (*OnlineBatchPushOneMsgResp, error)
	SuperGroupOnlineBatchPushOneMsg(ctx context.Context, in *OnlineBatchPushOneMsgReq, opts ...grpc.CallOption) (*OnlineBatchPushOneMsgResp, error)
	KickUserOffline(ctx context.Context, in *KickUserOfflineReq, opts ...grpc.CallOption) (*KickUserOfflineResp, error)
	MultiTerminalLoginCheck(ctx context.Context, in *MultiTerminalLoginCheckReq, opts ...grpc.CallOption) (*MultiTerminalLoginCheckResp, error)
}

type relayClient struct {
	cc *grpc.ClientConn
}

func NewRelayClient(cc *grpc.ClientConn) RelayClient {
	return &relayClient{cc}
}

func (c *relayClient) OnlinePushMsg(ctx context.Context, in *OnlinePushMsgReq, opts ...grpc.CallOption) (*OnlinePushMsgResp, error) {
	out := new(OnlinePushMsgResp)
	err := grpc.Invoke(ctx, "/relay.relay/OnlinePushMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) GetUsersOnlineStatus(ctx context.Context, in *GetUsersOnlineStatusReq, opts ...grpc.CallOption) (*GetUsersOnlineStatusResp, error) {
	out := new(GetUsersOnlineStatusResp)
	err := grpc.Invoke(ctx, "/relay.relay/GetUsersOnlineStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) OnlineBatchPushOneMsg(ctx context.Context, in *OnlineBatchPushOneMsgReq, opts ...grpc.CallOption) (*OnlineBatchPushOneMsgResp, error) {
	out := new(OnlineBatchPushOneMsgResp)
	err := grpc.Invoke(ctx, "/relay.relay/OnlineBatchPushOneMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) SuperGroupOnlineBatchPushOneMsg(ctx context.Context, in *OnlineBatchPushOneMsgReq, opts ...grpc.CallOption) (*OnlineBatchPushOneMsgResp, error) {
	out := new(OnlineBatchPushOneMsgResp)
	err := grpc.Invoke(ctx, "/relay.relay/SuperGroupOnlineBatchPushOneMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) KickUserOffline(ctx context.Context, in *KickUserOfflineReq, opts ...grpc.CallOption) (*KickUserOfflineResp, error) {
	out := new(KickUserOfflineResp)
	err := grpc.Invoke(ctx, "/relay.relay/KickUserOffline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) MultiTerminalLoginCheck(ctx context.Context, in *MultiTerminalLoginCheckReq, opts ...grpc.CallOption) (*MultiTerminalLoginCheckResp, error) {
	out := new(MultiTerminalLoginCheckResp)
	err := grpc.Invoke(ctx, "/relay.relay/MultiTerminalLoginCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Relay service

type RelayServer interface {
	OnlinePushMsg(context.Context, *OnlinePushMsgReq) (*OnlinePushMsgResp, error)
	GetUsersOnlineStatus(context.Context, *GetUsersOnlineStatusReq) (*GetUsersOnlineStatusResp, error)
	OnlineBatchPushOneMsg(context.Context, *OnlineBatchPushOneMsgReq) (*OnlineBatchPushOneMsgResp, error)
	SuperGroupOnlineBatchPushOneMsg(context.Context, *OnlineBatchPushOneMsgReq) (*OnlineBatchPushOneMsgResp, error)
	KickUserOffline(context.Context, *KickUserOfflineReq) (*KickUserOfflineResp, error)
	MultiTerminalLoginCheck(context.Context, *MultiTerminalLoginCheckReq) (*MultiTerminalLoginCheckResp, error)
}

func RegisterRelayServer(s *grpc.Server, srv RelayServer) {
	s.RegisterService(&_Relay_serviceDesc, srv)
}

func _Relay_OnlinePushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlinePushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).OnlinePushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relay.relay/OnlinePushMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).OnlinePushMsg(ctx, req.(*OnlinePushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_GetUsersOnlineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersOnlineStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).GetUsersOnlineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relay.relay/GetUsersOnlineStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).GetUsersOnlineStatus(ctx, req.(*GetUsersOnlineStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_OnlineBatchPushOneMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineBatchPushOneMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).OnlineBatchPushOneMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relay.relay/OnlineBatchPushOneMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).OnlineBatchPushOneMsg(ctx, req.(*OnlineBatchPushOneMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_SuperGroupOnlineBatchPushOneMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineBatchPushOneMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).SuperGroupOnlineBatchPushOneMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relay.relay/SuperGroupOnlineBatchPushOneMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).SuperGroupOnlineBatchPushOneMsg(ctx, req.(*OnlineBatchPushOneMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_KickUserOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickUserOfflineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).KickUserOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relay.relay/KickUserOffline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).KickUserOffline(ctx, req.(*KickUserOfflineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_MultiTerminalLoginCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiTerminalLoginCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).MultiTerminalLoginCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relay.relay/MultiTerminalLoginCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).MultiTerminalLoginCheck(ctx, req.(*MultiTerminalLoginCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Relay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "relay.relay",
	HandlerType: (*RelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnlinePushMsg",
			Handler:    _Relay_OnlinePushMsg_Handler,
		},
		{
			MethodName: "GetUsersOnlineStatus",
			Handler:    _Relay_GetUsersOnlineStatus_Handler,
		},
		{
			MethodName: "OnlineBatchPushOneMsg",
			Handler:    _Relay_OnlineBatchPushOneMsg_Handler,
		},
		{
			MethodName: "SuperGroupOnlineBatchPushOneMsg",
			Handler:    _Relay_SuperGroupOnlineBatchPushOneMsg_Handler,
		},
		{
			MethodName: "KickUserOffline",
			Handler:    _Relay_KickUserOffline_Handler,
		},
		{
			MethodName: "MultiTerminalLoginCheck",
			Handler:    _Relay_MultiTerminalLoginCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relay/relay.proto",
}

func init() { proto.RegisterFile("relay/relay.proto", fileDescriptor_relay_f693b13cb6a37b62) }

var fileDescriptor_relay_f693b13cb6a37b62 = []byte{
	// 827 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x4f, 0xe3, 0x46,
	0x18, 0x96, 0x49, 0xc2, 0xc7, 0x0b, 0xb4, 0x30, 0x85, 0xc6, 0xb8, 0x52, 0x12, 0x7c, 0xa8, 0xa2,
	0xaa, 0x24, 0x52, 0xda, 0x5b, 0x6f, 0x10, 0x41, 0xa3, 0x12, 0x05, 0x4d, 0xa8, 0x5a, 0xb1, 0x87,
	0xac, 0x49, 0x26, 0x89, 0x15, 0xc7, 0x1e, 0x66, 0x6c, 0x10, 0x97, 0xbd, 0xee, 0x65, 0xb5, 0x87,
	0xfd, 0x01, 0x7b, 0xd8, 0x3f, 0xb4, 0x7f, 0x69, 0x35, 0x1f, 0xf1, 0xda, 0x49, 0x4c, 0x96, 0x95,
	0xb8, 0x40, 0xde, 0xc7, 0xef, 0xd7, 0xf3, 0xbc, 0xaf, 0x67, 0x0c, 0xfb, 0x8c, 0x78, 0xce, 0x63,
	0x5d, 0xfe, 0xad, 0x51, 0x16, 0x84, 0x01, 0x2a, 0x48, 0xc3, 0xaa, 0x76, 0x28, 0xf1, 0x4f, 0x5a,
	0xed, 0x93, 0x2e, 0x61, 0xf7, 0x84, 0xd5, 0xe9, 0x64, 0x54, 0x97, 0x0e, 0x75, 0x3e, 0x98, 0xf4,
	0x1e, 0x78, 0xfd, 0x81, 0xab, 0x00, 0xfb, 0xbd, 0x01, 0x7b, 0x1d, 0xdf, 0x73, 0x7d, 0x72, 0x15,
	0xf1, 0x71, 0x9b, 0x8f, 0x30, 0xb9, 0x43, 0x15, 0xd8, 0xee, 0x50, 0xc2, 0x9c, 0xd0, 0x0d, 0xfc,
	0x56, 0xd3, 0x34, 0x2a, 0x46, 0x75, 0x0b, 0x27, 0x21, 0xf4, 0x27, 0x6c, 0x4c, 0xf9, 0xa8, 0xe9,
	0x84, 0x8e, 0xb9, 0x56, 0x31, 0xaa, 0xdb, 0x0d, 0xab, 0xc6, 0x65, 0xa9, 0x9e, 0x43, 0xdd, 0x1e,
	0x75, 0x98, 0x33, 0xe5, 0xb5, 0xb6, 0xf2, 0xc0, 0x33, 0x57, 0x64, 0xc3, 0x0e, 0x8d, 0xf8, 0xf8,
	0x3a, 0xf8, 0x97, 0x13, 0xd6, 0x6a, 0x9a, 0x39, 0x99, 0x38, 0x85, 0xd9, 0x17, 0xb0, 0x3f, 0xd7,
	0x0f, 0xa7, 0xa8, 0x01, 0x79, 0x46, 0x38, 0x35, 0x8d, 0x4a, 0xae, 0xba, 0xdd, 0x28, 0xd5, 0x14,
	0xe5, 0xae, 0xeb, 0x8f, 0x3c, 0xd2, 0xe6, 0x23, 0x15, 0x7c, 0xe5, 0x39, 0xe1, 0x30, 0x60, 0x53,
	0x2c, 0x7d, 0xed, 0xb7, 0x06, 0x1c, 0x09, 0x0f, 0xe2, 0xc5, 0x1e, 0x98, 0xf0, 0xc8, 0x0b, 0x2f,
	0x5d, 0x1e, 0xa2, 0x9f, 0x61, 0x3d, 0x52, 0x4d, 0x28, 0x76, 0xda, 0x8a, 0x2b, 0xad, 0x7d, 0x7b,
	0x25, 0x54, 0x02, 0x08, 0xe2, 0x96, 0x25, 0xa9, 0x4d, 0x9c, 0x40, 0xec, 0x8f, 0x06, 0x98, 0x8a,
	0xd3, 0xa9, 0x13, 0xf6, 0xc7, 0x02, 0xeb, 0xf8, 0xe4, 0x85, 0xb5, 0xfe, 0x0d, 0xf6, 0x92, 0xba,
	0x0a, 0xd2, 0x66, 0xae, 0x92, 0xab, 0x6e, 0xe1, 0x05, 0xdc, 0x76, 0xe1, 0x28, 0xa3, 0x3f, 0x4e,
	0xd1, 0x25, 0xec, 0x71, 0x49, 0x5f, 0xe0, 0x4a, 0x41, 0x3d, 0x87, 0x4a, 0x42, 0x9d, 0xa5, 0x2a,
	0xe3, 0x85, 0x48, 0xfb, 0x11, 0x8a, 0x19, 0x62, 0x0a, 0x19, 0x95, 0xd3, 0x59, 0x30, 0x20, 0x52,
	0x88, 0x1c, 0x4e, 0x20, 0x62, 0x64, 0x98, 0xf4, 0xef, 0x5b, 0x4d, 0x29, 0xc3, 0x16, 0xd6, 0x16,
	0xfa, 0x15, 0x7e, 0x10, 0xbf, 0x44, 0x9e, 0xf3, 0x80, 0x4d, 0xf5, 0x5e, 0x15, 0xf0, 0x1c, 0x6a,
	0x3f, 0x40, 0xf1, 0x82, 0x84, 0xa2, 0x24, 0x57, 0x6c, 0xbb, 0xa1, 0x13, 0x46, 0x5c, 0x0c, 0xa1,
	0x04, 0x10, 0x7d, 0x95, 0xc9, 0x90, 0x32, 0x25, 0x10, 0x31, 0xa4, 0x20, 0x31, 0x24, 0x55, 0x3f,
	0x09, 0x21, 0x0b, 0x36, 0x03, 0x9a, 0x5a, 0xeb, 0xd8, 0xb6, 0x3f, 0xe7, 0xc1, 0x5c, 0x5e, 0x99,
	0x53, 0x64, 0xc2, 0x06, 0x61, 0x2c, 0xa6, 0x5c, 0xc0, 0x33, 0x53, 0xf0, 0x25, 0x8c, 0xb5, 0xf9,
	0x68, 0xc6, 0x57, 0x59, 0xa8, 0x0b, 0xbb, 0x3c, 0xea, 0xf7, 0x09, 0xe7, 0x7a, 0x1a, 0x39, 0x39,
	0x8d, 0x13, 0x3d, 0x8d, 0xac, 0x4a, 0xb5, 0x6e, 0x32, 0x08, 0xa7, 0x73, 0xa0, 0x2b, 0xd8, 0x19,
	0x3a, 0xae, 0x47, 0x06, 0x3a, 0x67, 0x5e, 0xe6, 0xfc, 0x7d, 0x55, 0xce, 0x73, 0x19, 0xd3, 0x24,
	0xa1, 0xe3, 0x7a, 0x38, 0x95, 0xc1, 0x7a, 0x05, 0xbb, 0xba, 0xa2, 0x7a, 0x2c, 0x24, 0xa2, 0x7a,
	0xd6, 0x7a, 0xcd, 0x63, 0x5b, 0x70, 0xe5, 0x32, 0xeb, 0x8c, 0xab, 0xb2, 0x04, 0xde, 0x0f, 0x7c,
	0x3f, 0x16, 0x55, 0x5b, 0xd6, 0xff, 0xb0, 0x93, 0x2c, 0x9d, 0x78, 0x9d, 0x73, 0xa9, 0xd7, 0xf9,
	0xd9, 0xea, 0x5a, 0x9f, 0x8c, 0xb8, 0x6f, 0x2d, 0x4d, 0xd6, 0x51, 0x91, 0xd5, 0xb3, 0x03, 0x07,
	0x03, 0xd9, 0xd5, 0x6c, 0xb3, 0x95, 0x5e, 0xcf, 0x1c, 0x93, 0xd6, 0x74, 0x69, 0x2a, 0xfb, 0x0d,
	0xa0, 0x7f, 0xdc, 0xfe, 0x44, 0x24, 0xe8, 0x0c, 0x87, 0x22, 0x81, 0x3e, 0x4a, 0x82, 0xc5, 0xa3,
	0x24, 0xb9, 0xa5, 0x25, 0x80, 0x99, 0xe4, 0x7a, 0x8d, 0x0b, 0x38, 0x81, 0x88, 0x57, 0x69, 0xa2,
	0xf3, 0xa6, 0x8e, 0x8c, 0x39, 0xd4, 0x3e, 0x84, 0x9f, 0x16, 0xea, 0x73, 0x6a, 0xbf, 0x33, 0xc0,
	0x6a, 0x47, 0x5e, 0xe8, 0x5e, 0x13, 0x36, 0x75, 0x7d, 0xc7, 0xbb, 0x0c, 0x46, 0xae, 0x7f, 0x36,
	0x26, 0xfd, 0x89, 0xe8, 0x2f, 0x4b, 0xc8, 0x55, 0x5d, 0x1d, 0x40, 0x21, 0x0c, 0x26, 0xc4, 0xd7,
	0xb3, 0x55, 0xc6, 0x3c, 0xdb, 0xfc, 0x02, 0x5b, 0xbb, 0x03, 0xbf, 0x64, 0x76, 0xf3, 0x3d, 0x6f,
	0x5e, 0xe3, 0x43, 0x1e, 0xd4, 0x05, 0x8b, 0x4e, 0x61, 0x37, 0x75, 0x4b, 0xa1, 0xa2, 0x1e, 0xeb,
	0xfc, 0x5d, 0x6a, 0x99, 0xcb, 0x1f, 0x70, 0x8a, 0xfe, 0x83, 0x83, 0x65, 0x4b, 0x80, 0x4a, 0x4f,
	0x6e, 0xc8, 0x9d, 0x55, 0x5e, 0xb1, 0x41, 0xe8, 0x06, 0x0e, 0x97, 0x1e, 0xe7, 0xa8, 0x9c, 0xea,
	0x65, 0xf1, 0x32, 0xb2, 0x2a, 0x4f, 0x3b, 0x70, 0x8a, 0x06, 0x50, 0xee, 0x46, 0x94, 0xb0, 0x0b,
	0x16, 0x44, 0xf4, 0xc5, 0xaa, 0xfc, 0x0d, 0x3f, 0xce, 0xed, 0x17, 0x3a, 0xd2, 0x41, 0x8b, 0x7b,
	0x6f, 0x59, 0x59, 0x8f, 0x38, 0x45, 0xaf, 0xa1, 0x98, 0xb1, 0x03, 0xe8, 0x58, 0x87, 0x65, 0x6f,
	0xac, 0x65, 0xaf, 0x72, 0xe1, 0xf4, 0xf4, 0xf8, 0xa6, 0x2c, 0xbe, 0xb6, 0x7a, 0xad, 0x76, 0xe2,
	0x33, 0x4b, 0x86, 0xfd, 0x45, 0x6f, 0xb1, 0xf8, 0x7f, 0xbb, 0x2e, 0xc1, 0x3f, 0xbe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x2c, 0x2d, 0xc2, 0x83, 0xb1, 0x09, 0x00, 0x00,
}
