package callbackstruct

const CallbackBeforeInviteJoinGroupCommand = "callbackBeforeInviteJoinGroupCommand"
const CallbackAfterJoinGroupCommand = "callbackAfterJoinGroupCommand"
const CallbackAfterSetGroupInfoCommand = "callbackAfterSetGroupInfoCommand"
const CallbackBeforeSetGroupInfoCommand = "callbackBeforeSetGroupInfoCommand"

const CallbackAfterRevokeMsgCommand = "callbackBeforeAfterMsgCommand"
const CallbackBeforeAddBlackCommand = "callbackBeforeAddBlackCommand"
const CallbackAfterAddFriendCommand = "callbackAfterAddFriendCommand"
const CallbackBeforeAddFriendAgreeCommand = "callbackBeforeAddFriendAgreeCommand"

const CallbackAfterDeleteFriendCommand = "callbackAfterDeleteFriendCommand"
const CallbackBeforeImportFriendsCommand = "callbackBeforeImportFriendsCommand"
const CallbackAfterImportFriendsCommand = "callbackAfterImportFriendsCommand"
const CallbackAfterRemoveBlackCommand = "callbackAfterRemoveBlackCommand"

const (
	CallbackQuitGroupCommand                = "callbackQuitGroupCommand"
	CallbackKillGroupCommand                = "callbackKillGroupCommand"
	CallbackDisMissGroupCommand             = "callbackDisMissGroupCommand"
	CallbackBeforeJoinGroupCommand          = "callbackBeforeJoinGroupCommand"
	CallbackGroupMsgReadCommand             = "callbackGroupMsgReadCommand"
	CallbackMsgModifyCommand                = "callbackMsgModifyCommand"
	CallbackAfterUpdateUserInfoCommand      = "callbackAfterUpdateUserInfoCommand"
	CallbackBeforeUserRegisterCommand       = "callbackBeforeUserRegisterCommand"
	CallbackAfterUserRegisterCommand        = "callbackAfterUserRegisterCommand"
	CallbackTransferGroupOwnerAfter         = "callbackTransferGroupOwnerAfter"
	CallbackBeforeSetFriendRemark           = "callbackBeforeSetFriendRemark"
	CallbackAfterSetFriendRemark            = "callbackAfterSetFriendRemark"
	CallbackSingleMsgRead                   = "callbackSingleMsgRead"
	CallbackBeforeSendSingleMsgCommand      = "callbackBeforeSendSingleMsgCommand"
	CallbackAfterSendSingleMsgCommand       = "callbackAfterSendSingleMsgCommand"
	CallbackBeforeSendGroupMsgCommand       = "callbackBeforeSendGroupMsgCommand"
	CallbackAfterSendGroupMsgCommand        = "callbackAfterSendGroupMsgCommand"
	CallbackUserOnlineCommand               = "callbackUserOnlineCommand"
	CallbackUserOfflineCommand              = "callbackUserOfflineCommand"
	CallbackUserKickOffCommand              = "callbackUserKickOffCommand"
	CallbackOfflinePushCommand              = "callbackOfflinePushCommand"
	CallbackOnlinePushCommand               = "callbackOnlinePushCommand"
	CallbackSuperGroupOnlinePushCommand     = "callbackSuperGroupOnlinePushCommand"
	CallbackBeforeAddFriendCommand          = "callbackBeforeAddFriendCommand"
	CallbackBeforeUpdateUserInfoCommand     = "callbackBeforeUpdateUserInfoCommand"
	CallbackBeforeCreateGroupCommand        = "callbackBeforeCreateGroupCommand"
	CallbackAfterCreateGroupCommand         = "callbackAfterCreateGroupCommand"
	CallbackBeforeMemberJoinGroupCommand    = "callbackBeforeMemberJoinGroupCommand"
	CallbackBeforeSetGroupMemberInfoCommand = "callbackBeforeSetGroupMemberInfoCommand"
	CallbackAfterSetGroupMemberInfoCommand  = "callbackAfterSetGroupMemberInfoCommand"
)
