package callbackstruct

const CallbackBeforeInviteJoinGroupCommand = "CallbackBeforeInviteJoinGroupCommand"
const CallbackAfterJoinGroupCommand = "CallbackAfterJoinGroupCommand"
const CallbackAfterSetGroupInfoCommand = "CallbackAfterSetGroupInfoCommand"
const CallbackBeforeSetGroupInfoCommand = "CallbackBeforeSetGroupInfoCommand"

const CallbackAfterRevokeMsgCommand = "CallbackBeforeAfterMsgCommand"
const CallbackBeforeAddBlackCommand = "CallbackBeforeAddBlackCommand"
const CallbackAfterAddFriendCommand = "CallbackAfterAddFriendCommand"
const CallbackBeforeAddFriendAgreeCommand = "CallbackBeforeAddFriendAgreeCommand"

const CallbackAfterDeleteFriendCommand = "CallbackAfterDeleteFriendCommand"
const CallbackBeforeImportFriendsCommand = "CallbackBeforeImportFriendsCommand"
const CallbackAfterImportFriendsCommand = "CallbackAfterImportFriendsCommand"
const CallbackAfterRemoveBlackCommand = "CallbackAfterRemoveBlackCommand"

const (
	CallbackQuitGroupCommand                = "callbackQuitGroupCommand"
	CallbackKillGroupCommand                = "callbackKillGroupCommand"
	CallbackDisMissGroupCommand             = "callbackDisMissGroupCommand"
	CallbackBeforeJoinGroupCommand          = "callbackBeforeJoinGroupCommand"
	CallbackGroupMsgReadCommand             = "callbackGroupMsgReadCommand"
	CallbackMsgModifyCommand                = "callbackMsgModifyCommand"
	CallbackAfterUpdateUserInfoCommand      = "callbackAfterUpdateUserInfoCommand"
	CallbackBeforeUserRegisterCommand       = "callbackBeforeUserRegisterCommand"
	CallbackAfterUserRegisterCommand        = "callbackAfterUserRegisterCommand"
	CallbackTransferGroupOwnerAfter         = "callbackTransferGroupOwnerAfter"
	CallbackBeforeSetFriendRemark           = "callbackBeforeSetFriendRemark"
	CallbackAfterSetFriendRemark            = "callbackAfterSetFriendRemark"
	CallbackSingleMsgRead                   = "callbackSingleMsgRead"
	CallbackBeforeSendSingleMsgCommand      = "callbackBeforeSendSingleMsgCommand"
	CallbackAfterSendSingleMsgCommand       = "callbackAfterSendSingleMsgCommand"
	CallbackBeforeSendGroupMsgCommand       = "callbackBeforeSendGroupMsgCommand"
	CallbackAfterSendGroupMsgCommand        = "callbackAfterSendGroupMsgCommand"
	CallbackUserOnlineCommand               = "callbackUserOnlineCommand"
	CallbackUserOfflineCommand              = "callbackUserOfflineCommand"
	CallbackUserKickOffCommand              = "callbackUserKickOffCommand"
	CallbackOfflinePushCommand              = "callbackOfflinePushCommand"
	CallbackOnlinePushCommand               = "callbackOnlinePushCommand"
	CallbackSuperGroupOnlinePushCommand     = "callbackSuperGroupOnlinePushCommand"
	CallbackBeforeAddFriendCommand          = "callbackBeforeAddFriendCommand"
	CallbackBeforeUpdateUserInfoCommand     = "callbackBeforeUpdateUserInfoCommand"
	CallbackBeforeCreateGroupCommand        = "callbackBeforeCreateGroupCommand"
	CallbackAfterCreateGroupCommand         = "callbackAfterCreateGroupCommand"
	CallbackBeforeMemberJoinGroupCommand    = "callbackBeforeMemberJoinGroupCommand"
	CallbackBeforeSetGroupMemberInfoCommand = "CallbackBeforeSetGroupMemberInfoCommand"
)
