go build -o api.exe ../cmd/openim-api/main.go
go build -o auth.exe ../cmd/openim-rpc/openim-rpc-auth/main.go
go build -o conversation.exe ../cmd/openim-rpc/openim-rpc-conversation/main.go
go build -o friend.exe ../cmd/openim-rpc/openim-rpc-friend/main.go
go build -o group.exe ../cmd/openim-rpc/openim-rpc-group/main.go
go build -o msg.exe ../cmd/openim-rpc/openim-rpc-msg/main.go
go build -o third.exe ../cmd/openim-rpc/openim-rpc-third/main.go
go build -o user.exe ../cmd/openim-rpc/openim-rpc-user/main.go
go build -o push.exe ../cmd/openim-push/main.go
go build -o msgtransfer.exe ../cmd/openim-msgtransfer/main.go
go build -o msggateway.exe ../cmd/openim-msggateway/main.go
