// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push/push.proto

package pbPush // import "OpenIM/pkg/proto/push"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import sdkws "OpenIM/pkg/proto/sdkws"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PushMsgReq struct {
	MsgData              *sdkws.MsgData `protobuf:"bytes,1,opt,name=msgData" json:"msgData,omitempty"`
	SourceID             string         `protobuf:"bytes,2,opt,name=sourceID" json:"sourceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_push_8111188de42e41d8, []int{0}
}
func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (dst *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(dst, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetMsgData() *sdkws.MsgData {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *PushMsgReq) GetSourceID() string {
	if m != nil {
		return m.SourceID
	}
	return ""
}

type PushMsgResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgResp) Reset()         { *m = PushMsgResp{} }
func (m *PushMsgResp) String() string { return proto.CompactTextString(m) }
func (*PushMsgResp) ProtoMessage()    {}
func (*PushMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_push_8111188de42e41d8, []int{1}
}
func (m *PushMsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgResp.Unmarshal(m, b)
}
func (m *PushMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgResp.Marshal(b, m, deterministic)
}
func (dst *PushMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgResp.Merge(dst, src)
}
func (m *PushMsgResp) XXX_Size() int {
	return xxx_messageInfo_PushMsgResp.Size(m)
}
func (m *PushMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgResp proto.InternalMessageInfo

type DelUserPushTokenReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	PlatformID           int32    `protobuf:"varint,2,opt,name=platformID" json:"platformID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserPushTokenReq) Reset()         { *m = DelUserPushTokenReq{} }
func (m *DelUserPushTokenReq) String() string { return proto.CompactTextString(m) }
func (*DelUserPushTokenReq) ProtoMessage()    {}
func (*DelUserPushTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_push_8111188de42e41d8, []int{2}
}
func (m *DelUserPushTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserPushTokenReq.Unmarshal(m, b)
}
func (m *DelUserPushTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserPushTokenReq.Marshal(b, m, deterministic)
}
func (dst *DelUserPushTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserPushTokenReq.Merge(dst, src)
}
func (m *DelUserPushTokenReq) XXX_Size() int {
	return xxx_messageInfo_DelUserPushTokenReq.Size(m)
}
func (m *DelUserPushTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserPushTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserPushTokenReq proto.InternalMessageInfo

func (m *DelUserPushTokenReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DelUserPushTokenReq) GetPlatformID() int32 {
	if m != nil {
		return m.PlatformID
	}
	return 0
}

type DelUserPushTokenResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserPushTokenResp) Reset()         { *m = DelUserPushTokenResp{} }
func (m *DelUserPushTokenResp) String() string { return proto.CompactTextString(m) }
func (*DelUserPushTokenResp) ProtoMessage()    {}
func (*DelUserPushTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_push_8111188de42e41d8, []int{3}
}
func (m *DelUserPushTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserPushTokenResp.Unmarshal(m, b)
}
func (m *DelUserPushTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserPushTokenResp.Marshal(b, m, deterministic)
}
func (dst *DelUserPushTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserPushTokenResp.Merge(dst, src)
}
func (m *DelUserPushTokenResp) XXX_Size() int {
	return xxx_messageInfo_DelUserPushTokenResp.Size(m)
}
func (m *DelUserPushTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserPushTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserPushTokenResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PushMsgReq)(nil), "push.PushMsgReq")
	proto.RegisterType((*PushMsgResp)(nil), "push.PushMsgResp")
	proto.RegisterType((*DelUserPushTokenReq)(nil), "push.DelUserPushTokenReq")
	proto.RegisterType((*DelUserPushTokenResp)(nil), "push.DelUserPushTokenResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PushMsgService service

type PushMsgServiceClient interface {
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error)
	DelUserPushToken(ctx context.Context, in *DelUserPushTokenReq, opts ...grpc.CallOption) (*DelUserPushTokenResp, error)
}

type pushMsgServiceClient struct {
	cc *grpc.ClientConn
}

func NewPushMsgServiceClient(cc *grpc.ClientConn) PushMsgServiceClient {
	return &pushMsgServiceClient{cc}
}

func (c *pushMsgServiceClient) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error) {
	out := new(PushMsgResp)
	err := grpc.Invoke(ctx, "/push.PushMsgService/PushMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) DelUserPushToken(ctx context.Context, in *DelUserPushTokenReq, opts ...grpc.CallOption) (*DelUserPushTokenResp, error) {
	out := new(DelUserPushTokenResp)
	err := grpc.Invoke(ctx, "/push.PushMsgService/DelUserPushToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PushMsgService service

type PushMsgServiceServer interface {
	PushMsg(context.Context, *PushMsgReq) (*PushMsgResp, error)
	DelUserPushToken(context.Context, *DelUserPushTokenReq) (*DelUserPushTokenResp, error)
}

func RegisterPushMsgServiceServer(s *grpc.Server, srv PushMsgServiceServer) {
	s.RegisterService(&_PushMsgService_serviceDesc, srv)
}

func _PushMsgService_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.PushMsgService/PushMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).PushMsg(ctx, req.(*PushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_DelUserPushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserPushTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).DelUserPushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.PushMsgService/DelUserPushToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).DelUserPushToken(ctx, req.(*DelUserPushTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PushMsgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "push.PushMsgService",
	HandlerType: (*PushMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMsg",
			Handler:    _PushMsgService_PushMsg_Handler,
		},
		{
			MethodName: "DelUserPushToken",
			Handler:    _PushMsgService_DelUserPushToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push/push.proto",
}

func init() { proto.RegisterFile("push/push.proto", fileDescriptor_push_8111188de42e41d8) }

var fileDescriptor_push_8111188de42e41d8 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xd3, 0x7f, 0xfe, 0x82, 0x0c, 0x11, 0x71, 0x35, 0x04, 0x1b, 0x43, 0x48, 0x2f, 0xf6,
	0x42, 0x9b, 0xe0, 0xd1, 0x9b, 0xe9, 0xa5, 0x87, 0x8d, 0x66, 0xd5, 0x8b, 0xb7, 0x82, 0x63, 0x31,
	0x05, 0x76, 0xdc, 0x69, 0xe5, 0x43, 0xf8, 0xa5, 0xcd, 0x6e, 0x2b, 0x12, 0xd4, 0x4b, 0xd3, 0xf9,
	0xcd, 0xcb, 0x7b, 0x79, 0xb3, 0x70, 0x4c, 0x15, 0x2f, 0x62, 0xfb, 0x89, 0xc8, 0xe8, 0x52, 0x8b,
	0xff, 0xf6, 0xdf, 0xbf, 0xbc, 0x25, 0x5c, 0x4f, 0x52, 0x39, 0xb9, 0x47, 0xf3, 0x8e, 0x26, 0xa6,
	0x22, 0x8f, 0xdd, 0x3e, 0xe6, 0xe7, 0x62, 0xc3, 0xf1, 0x86, 0x6b, 0x79, 0xa0, 0x00, 0xee, 0x2a,
	0x5e, 0x48, 0xce, 0x15, 0xbe, 0x89, 0x10, 0xda, 0x2b, 0xce, 0x93, 0xac, 0xcc, 0x86, 0xde, 0xd8,
	0x0b, 0xbb, 0xd3, 0x5e, 0xe4, 0xf4, 0x91, 0xac, 0xa9, 0xfa, 0x5a, 0x0b, 0x1f, 0x0e, 0x59, 0x57,
	0x66, 0x8e, 0x69, 0x32, 0xfc, 0x37, 0xf6, 0xc2, 0x8e, 0xda, 0xce, 0xc1, 0x11, 0x74, 0xb7, 0x9e,
	0x4c, 0x81, 0x84, 0xd3, 0x04, 0x97, 0x8f, 0x8c, 0xc6, 0xd2, 0x07, 0x5d, 0xe0, 0xda, 0x66, 0x0d,
	0xa0, 0x55, 0x31, 0x9a, 0x34, 0x71, 0x51, 0x1d, 0xd5, 0x4c, 0x62, 0x04, 0x40, 0xcb, 0xac, 0x7c,
	0xd1, 0x66, 0xd5, 0x78, 0x1f, 0xa8, 0x1d, 0x12, 0x0c, 0xe0, 0xec, 0xa7, 0x1d, 0xd3, 0xf4, 0xc3,
	0x83, 0x5e, 0x13, 0x6b, 0x4b, 0xbf, 0xce, 0x51, 0x44, 0xd0, 0x6e, 0x88, 0xe8, 0x47, 0xee, 0x46,
	0xdf, 0x5d, 0xfd, 0x93, 0x3d, 0xc2, 0x24, 0x52, 0xe8, 0xef, 0x5b, 0x8b, 0xf3, 0x5a, 0xf6, 0x4b,
	0x03, 0xdf, 0xff, 0x6b, 0xc5, 0x74, 0x33, 0x7a, 0xba, 0xb0, 0x4f, 0x90, 0xca, 0x9d, 0xd3, 0x5b,
	0xf5, 0x35, 0xcd, 0xac, 0x70, 0xd6, 0x72, 0xe8, 0xea, 0x33, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x9e,
	0x84, 0x31, 0xc0, 0x01, 0x00, 0x00,
}
