{
 "title": "docker-openim-custom1",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes,job) "
    }
   },
   { "name": "interval", "query": "1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "openim Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online population",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(online_user_num{job=~\"^($job)$\"})",
     "legendFormat": "online_user_num"
    }
   ]
  },
  {
   "title": "Login/registration numbers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(user_login_total{job=~\"^($job)$\"})",
     "legendFormat": "user_login_total"
    }
   ]
  },
  {
   "title": "failues/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(single_chat_msg_process_failed_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-single_chat_msg_process_failed"
    },
    {
     "expr": "sum(rate(group_chat_msg_process_failed_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-group_chat_msg_process_failed"
    },
    {
     "expr": "sum(rate(msg_offline_push_failed_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-msg_offline_push_failed"
    },
    {
     "expr": "sum(rate(msg_insert_redis_failed_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-msg_insert_redis_failed"
    },
    {
     "expr": "sum(rate(msg_insert_mongo_failed_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-msg_insert_mongo_failed"
    },
    {
     "expr": "sum(rate(seq_set_failed_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-seq_set_failed"
    }
   ]
  },
  {
   "title": "messages/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(single_chat_msg_process_success_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-single_chat_msg_process_success"
    },
    {
     "expr": "sum(rate(group_chat_msg_process_success_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-group_chat_msg_process_success"
    },
    {
     "expr": "sum(rate(msg_insert_redis_success_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-msg_insert_redis_success"
    },
    {
     "expr": "sum(rate(msg_insert_mongo_success_total{job=~\"^($job)$\"}[$interval])) by (job)",
     "legendFormat": "{{job}}-msg_insert_mongo_success"
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(go_goroutines{job=~\"^($job)$\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"^($job)$\",quantile=\"1\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes{job=~\"^($job)$\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=~\"^($job)$\"})by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Traffic indicators of the application server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Up",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(up{job=~\"^($job)$\"})by(job)",
       "legendFormat": "{{job}}-up"
      }
     ]
    },
    {
     "title": "failures/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(app_requests_total{job=~\"^($job)$\", code!~\"200\"}[$interval])) by (job)",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{job=~\"^($job)$\",grpc_code!~\"OK\"}[$interval])) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "qps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "req/s" } },
     "targets": [
      {
       "expr": "sum(rate(app_requests_total{job=~\"^($job)$\"}[$interval])) by (job)",
       "legendFormat": "{{job}}-webhook"
      },
      {
       "expr": "sum(rate(grpc_server_started_total{job=~\"^($job)$\"}[$interval])) by (job)",
       "legendFormat": "{{job}}-grpc"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \r\n  sum(rate(app_request_duration_seconds_bucket{job=~\"^($job)$\"}[$interval])) \r\n  by (le, job)\r\n)",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, \r\n  sum(rate(grpc_server_handling_seconds_bucket{job=~\"^($job)$\"}[$interval])) \r\n  by (le, job)\r\n)",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}